function love.conf(t)
    t.window.title = "Aether-Starter-Template" -- The title of the window the game is in (string)
    t.window.author = "Kolyne"                 -- The author of the game (string)
    t.window.width = 1280                      -- The window width (number)
    t.window.height = 720                      -- The window height (number)
    t.window.fullscreen = false                -- Fullscreen (boolean)
    t.window.vsync = 0                         -- Vertical sync mode (number)
    t.modules.joystick = true                  -- Enable the joystick module (boolean)
    t.modules.keyboard = true                  -- Enable the keyboard module (boolean)
    t.modules.event = true                     -- Enable the event module (boolean)
    t.modules.image = true                     -- Enable the image module (boolean)
    t.modules.graphics = true                  -- Enable the graphics module (boolean)
    t.modules.timer = true                     -- Enable the timer module (boolean)
    t.modules.mouse = true                     -- Enable the mouse module (boolean)
end
